include $(TOPDIR)/rules.mk

PKG_VERSION:=0.1
PKG_RELEASE:=1

LUCI_TITLE:=LuCi interface for tuya_daemon
LUCI_DEPENDS:=+tuya_daemon

include $(TOPDIR)/feeds/luci/luci.mk

# call BuildPackage - OpenWrt buildroot signature
