#!/bin/sh /etc/rc.common

START=50
USE_PROCD=1

start_service() {
	local enabled

	config_load 'tuya'
	config_get enabled tuya_daemon 'enabled' '0'

	if [ "$enabled" -eq 1 ]; then
		procd_open_instance
		procd_set_param command /usr/bin/tuya_daemon
		procd_set_param pidfile /var/run/tuya_daemon.pid
		procd_set_param file /etc/config/tuya
		procd_close_instance
	fi
}

service_triggers() {
	procd_add_reload_trigger "tuya"
}

reload_service() {
	stop
	start
}
